### ISSUE TITLE
NullReferenceException at EditorConfig.EditorConfigQuickInfoControllerProvider.TryCreateIntellisenseController

### ISSUE THREAD

**Issue by nnpcYvIVl** [madskristensen/EditorConfigLanguage#49]
### Installed product versions
- Visual Studio: 2017 Enterprise 17.8.1
- This extension: 1.17.242

### Description
When opening an editorconfig file in diff mode the IDE showed an error message like "Extension failed to load. Please see ActivityLog.xml". Inside of the XML file was this error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at EditorConfig.EditorConfigQuickInfoControllerProvider.TryCreateIntellisenseController(ITextView textView, IList`1 subjectBuffers) in C:\projects\editorconfiglanguage\src\QuickInfo\EditorConfigQuickInfoControllerProvider.cs:line 0
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.IntellisenseManagerConnectionListener.<>c__DisplayClass8_1.<SubjectBuffersConnected>b__1(IIntellisenseControllerProvider provider)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)
```

### Steps to recreate
I haven't tried to reproduce it yet.

**Comment by zadigus** [comment]
Any progress there? I have the same issue.
